"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from . import utils

cache_maxsize = ...

def lru_cache_freezeargs(
    func,
):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """
    Decorator transforms mutable dictionary and list arguments into immutable types
    Needed so lru_cache can cache method calls what has dict or list arguments.
    """
    ...

class SingletonMeta(type):
    """
    Metaclass that creates a Singleton instance.
    """

    _instances = ...
    _lock = ...
    def __call__(cls, *args, **kwargs): ...

class YfData(metaclass=SingletonMeta):
    """
    Have one place to retrieve data from Yahoo API in order to ease caching and speed up operations.
    Singleton means one session one cookie shared by all threads.
    """

    def __init__(self, session=...) -> None: ...
    @utils.log_indent_decorator
    def get(self, url, params=..., timeout=...):  # -> Response:
        ...

    @utils.log_indent_decorator
    def post(self, url, body=..., params=..., timeout=..., data=...): ...
    @lru_cache_freezeargs
    @lru_cache(maxsize=cache_maxsize)
    def cache_get(self, url, params=..., timeout=...):  # -> Response:
        ...

    def get_raw_json(self, url, params=..., timeout=...):  # -> Any:
        ...
