"""
This type stub file was generated by pyright.
"""

class Market:
    def __init__(self, market: str, session=..., timeout=...) -> None: ...
    @property
    def status(self):  # -> Any | dict[Any, Any] | None:
        ...

    @property
    def summary(self):  # -> Any | dict[Any, Any] | None:
        ...
